package classify

var folders = []string{"Images", "Music", "Videos", "Documents", "Archives"}

var extensions = map[string]string{
	".jpg":  "Images",
	".jpeg": "Images",
	".png":  "Images",
	".gif":  "Images",
	".webp": "Images",
	".tiff": "Images",
	".tif":  "Images",
	".ico":  "Images",
	".heic": "Images",
	".svg":  "Images",
	".mp3":  "Music",
	".m4a":  "Music",
	".wav":  "Music",
	".flac": "Music",
	".aac":  "Music",
	".opus": "Music",
	".ogg":  "Music",
	".mp4":  "Videos",
	".mkv":  "Videos",
	".avi":  "Videos",
	".mov":  "Videos",
	".webm": "Videos",
	".pdf":  "Documents",
	".doc":  "Documents",
	".docx": "Documents",
	".xls":  "Documents",
	".xlsx": "Documents",
	".ppt":  "Documents",
	".pptx": "Documents",
	".txt":  "Documents",
	".csv":  "Documents",
	".md":   "Documents",
	".epub": "Documents",
	".zip":  "Archives",
	".tar":  "Archives",
	".gz":   "Archives",
	".7z":   "Archives",
	".rar":  "Archives",
	".tgz":  "Archives",
}
